# Generated by Django 3.1 on 2023-01-23 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 0, 39, 40, 270260)),
        ),
    ]
